require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Rails/ApplicationController:
  Exclude:
    - spec/support/controllers.rb

Rails/ApplicationRecord:
  Exclude:
    - lib/rabarber/models/role.rb
    - spec/support/models.rb

RSpec/ContextWording:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Lambda:
  Enabled: true
  EnforcedStyle: literal

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: true
  EnforcedStyle: brackets

Style/WordArray:
  Enabled: true
  EnforcedStyle: brackets
